version: '3.9'

services:
  postgres:
    image: postgres:14
    env_file:
      - '.env'
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3.11.7-management
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis:7.0.8
    restart: always
    ports:
      - '6379:6379'

  celery:
    build: .
    command: celery -A worker.app worker
    env_file:
      - '.env'
    depends_on:
      - redis
      - rabbitmq

  flower:
    build: .
    command: celery flower -A worker.app --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
    ports:
      - '5555:5555'
    env_file:
      - '.env'
    depends_on:
      - rabbitmq
